# -*- coding: utf-8 -*-
"""Classify a business into (Category Group, Subcategory) from its Google
category label and name. Rules are ordered: first match wins."""
import re

RULES = [
("Health & Medical","Dentists",["dentist","dental","orthodont"]),
("Health & Medical","Pharmacies",["pharmac","chemist"]),
("Health & Medical","Patent Medicine Stores",["patent medicine"]),
("Health & Medical","Laboratories",["laborator","patholog"]),
("Health & Medical","Diagnostic Centres",["diagnost","radiolog"]),
("Health & Medical","Opticians",["optic","optometr","eye clinic","eye cent"]),
("Health & Medical","Physiotherapy",["physiotherap","physical therap","chiroprac"]),
("Health & Medical","Maternity Services",["maternity","obstetric","fertility","midwife"]),
("Health & Medical","Medical Equipment Suppliers",["medical equipment","medical supply","medical supplies"]),
("Health & Medical","Home Nursing Services",["home nursing","nursing service"]),
("Health & Medical","Home-Care Services",["home care","homecare","home-care"]),
("Health & Medical","Hospitals",["hospital"]),
("Health & Medical","Clinics",["clinic","medical cent","medical center","health cent","doctor","physician","medical group","medical practice"]),
("Beauty & Personal Care","Barbers",["barb"]),
("Beauty & Personal Care","Braiders",["braid"]),
("Beauty & Personal Care","Wig Makers",["wig"]),
("Beauty & Personal Care","Nail Technicians",["nail"]),
("Beauty & Personal Care","Lash Technicians",["lash"]),
("Beauty & Personal Care","Brow Specialists",["brow","threading"]),
("Beauty & Personal Care","Makeup Artists",["makeup","make-up","make up artist"]),
("Beauty & Personal Care","Spas",["spa"]),
("Beauty & Personal Care","Massage Services",["massage"]),
("Beauty & Personal Care","Waxing Services",["waxing"]),
("Beauty & Personal Care","Skincare Businesses",["skin care","skincare","facial","aesthetic","dermatolog"]),
("Beauty & Personal Care","Beauty Product Retailers",["beauty supply","cosmetics store","cosmetic store","perfume","beauty product"]),
("Beauty & Personal Care","Hair Salons",["hair","salon","saloon","hairdress","stylist"]),
("Fitness & Wellness","Yoga",["yoga"]),
("Fitness & Wellness","Pilates",["pilates"]),
("Fitness & Wellness","Dance Studios",["dance"]),
("Fitness & Wellness","Martial Arts",["martial art","karate","taekwondo","judo","boxing"]),
("Fitness & Wellness","Personal Trainers",["personal train"]),
("Fitness & Wellness","Nutrition/Diet Services",["nutrition","dietit","dietic","weight loss","weight manage"]),
("Fitness & Wellness","Sports Coaching",["sports club","sports comple","football academy","sport coach","athletic"]),
("Fitness & Wellness","Wellness Centres",["wellness"]),
("Fitness & Wellness","Gyms",["gym","fitness"]),
("Education & Children","Daycare Centres",["daycare","day care","day-care"]),
("Education & Children","Creches",["creche"]),
("Education & Children","Montessori Schools",["montessori"]),
("Education & Children","Nursery Schools",["nursery","preschool","pre-school","kindergarten"]),
("Education & Children","Secondary Schools",["secondary school","high school","college","grammar school"]),
("Education & Children","Primary Schools",["primary school","elementary school"]),
("Education & Children","Computer Training",["computer training","ict training","coding school","aptech","software training"]),
("Education & Children","Music Schools",["music school","music academy","music lesson"]),
("Education & Children","Vocational Training",["vocational","skill acquisition","trade school","catering school","fashion school","beauty school"]),
("Education & Children","Tutoring Centres",["tutorial","tutor","lesson","exam prep","jamb","waec","coaching cent"]),
("Education & Children","Children's Activity Centres",["children","kids","playground","activity cent"]),
("Education & Children","Nursery Schools",["school","academy","educat","institute","university","polytechnic"]),
("Religious & Community","Mosques",["mosque","islamic cent"]),
("Religious & Community","Churches",["church","parish","chapel","cathedral","assembl","tabernacle","gospel"]),
("Religious & Community","Ministries",["ministr","mission","evangel","crusade"]),
("Religious & Community","Fellowship Centres",["fellowship","prayer"]),
("Religious & Community","Religious Bookshops",["christian book","islamic book","religious book"]),
("Religious & Community","Community Centres",["community cent","town hall","civic cent"]),
("Religious & Community","Social Clubs",["social club","members club","recreation club"]),
("Religious & Community","Residents' Associations",["residents","landlord association","community associat"]),
("Automotive","Vulcanisers",["vulcani"]),
("Automotive","Panel Beaters",["panel beat","auto body","body shop"]),
("Automotive","Spray Painters",["spray paint","car paint"]),
("Automotive","Tyre Dealers",["tyre","tire"]),
("Automotive","Wheel Alignment",["wheel align","wheel balanc"]),
("Automotive","Battery Dealers",["car battery","auto battery","battery shop","battery deal"]),
("Automotive","Auto AC Services",["auto air condition","car air condition","auto ac"]),
("Automotive","Car Diagnostics",["car diagnos","auto diagnos","car inspection"]),
("Automotive","Spare Parts Dealers",["spare part","auto part","car part"]),
("Automotive","Car Accessories",["car accessor","auto accessor"]),
("Automotive","Car Detailing",["detailing","car groom"]),
("Automotive","Car Wash",["car wash","carwash"]),
("Automotive","Car Rental Services",["car rental","car hire","rent a car","vehicle rental"]),
("Automotive","Motorcycle Repairers",["motorcycle","okada","bike repair"]),
("Automotive","Auto Electricians",["auto electric","car electric"]),
("Automotive","Mechanics",["mechanic","auto repair","car repair","auto works","autoworks","automobile","auto serv","motor"]),
("Power & Energy","Solar Installers",["solar"]),
("Power & Energy","Inverter Suppliers",["inverter"]),
("Power & Energy","Generator Repairers",["generator repair","generator servic","generator technician"]),
("Power & Energy","Generator Dealers",["generator"]),
("Power & Energy","Diesel/Fuel Suppliers",["diesel","fuel supply","petrol station","filling station","gas station"]),
("Power & Energy","Electrical Contractors",["electrical contract","electrical engineer","electrical servic"]),
("Construction & Building","Plumbers",["plumb"]),
("Construction & Building","Welders",["weld"]),
("Construction & Building","Aluminium Fabricators",["aluminium","aluminum"]),
("Construction & Building","Glass Installers",["glass","glazing"]),
("Construction & Building","Tilers",["tiler","tiling","tiles"]),
("Construction & Building","POP Installers",["pop ceiling","screeding"]),
("Construction & Building","Roofing Contractors",["roofing"]),
("Construction & Building","Waterproofing Services",["waterproof"]),
("Construction & Building","Steel Fabricators",["steel","iron bend","metal fabricat"]),
("Construction & Building","Brick/Block Suppliers",["block industry","block making","brick"]),
("Construction & Building","Building Material Shops",["building material","cement","hardware store","hardware shop"]),
("Construction & Building","Painters",["painter","painting contract"]),
("Construction & Building","Building Contractors",["contractor","construction","civil engineer","builder"]),
("Furniture & Interiors","Mattress Shops",["mattress","foam"]),
("Furniture & Interiors","Kitchen Cabinet Makers",["kitchen cabinet","kitchen fitting"]),
("Furniture & Interiors","Wardrobe Makers",["wardrobe"]),
("Furniture & Interiors","Curtain Suppliers",["curtain","drapery"]),
("Furniture & Interiors","Blinds Suppliers",["blinds"]),
("Furniture & Interiors","Wallpaper Installers",["wallpaper"]),
("Furniture & Interiors","Interior Designers",["interior design","interior decor"]),
("Furniture & Interiors","Upholsterers",["upholster"]),
("Furniture & Interiors","Carpenters",["carpent","woodwork","joinery"]),
("Furniture & Interiors","Office Furniture",["office furniture"]),
("Furniture & Interiors","Lighting Shops",["lighting","chandelier"]),
("Furniture & Interiors","Kitchen Equipment Suppliers",["kitchen equipment","catering equipment"]),
("Furniture & Interiors","Home Decor Shops",["home decor","decor store"]),
("Furniture & Interiors","Furniture Shops",["furniture"]),
("Home Services","AC Repair",["air conditioner repair","ac repair","hvac"]),
("Home Services","AC Installation",["air conditioning","air condition"]),
("Home Services","Refrigeration Services",["refrigerat","fridge repair","freezer repair"]),
("Home Services","Appliance Repair",["appliance"]),
("Home Services","Locksmiths",["locksmith","key cutting"]),
("Home Services","Pest Control",["pest control","fumigat","exterminat"]),
("Home Services","Borehole Services",["borehole","water drilling"]),
("Home Services","Water Treatment",["water treatment","water purif"]),
("Home Services","Water Tank Suppliers",["water tank","tank supplier"]),
("Home Services","Domestic Staff Agencies",["domestic staff","maid agency"]),
("Home Services","Nanny Services",["nanny","au pair"]),
("Home Services","Elderly Care Services",["elderly","senior care"]),
("Home Services","Handyman Services",["handyman","home repair","home maintenance"]),
("Laundry & Cleaning","Dry Cleaners",["dry clean","drycleaner","dry-clean"]),
("Laundry & Cleaning","Carpet Cleaning",["carpet clean","rug clean"]),
("Laundry & Cleaning","Upholstery Cleaning",["upholstery clean","sofa clean"]),
("Laundry & Cleaning","Office Cleaning",["office clean","commercial clean"]),
("Laundry & Cleaning","Shoe Cleaning",["shoe clean","sneaker clean"]),
("Laundry & Cleaning","Laundry Businesses",["laundr","launder","washing servic"]),
("Laundry & Cleaning","Residential Cleaning",["clean"]),
("Security","CCTV Installers",["cctv","surveillance camera"]),
("Security","Alarm Systems",["alarm"]),
("Security","Access Control",["access control","turnstile"]),
("Security","Gate Automation",["gate automation","automatic gate"]),
("Security","Electric Fence Installers",["electric fence"]),
("Security","Security Equipment Suppliers",["security equipment","security gadget"]),
("Security","Private Security Guards",["security guard","guard servic"]),
("Security","Security Companies",["security"]),
("Logistics & Delivery","Courier Services",["courier","dhl","fedex"]),
("Logistics & Delivery","Dispatch Riders",["dispatch"]),
("Logistics & Delivery","Haulage Companies",["haulage","truck"]),
("Logistics & Delivery","Moving Companies",["moving","relocation","mover"]),
("Logistics & Delivery","Errand Services",["errand","personal shopper"]),
("Logistics & Delivery","Delivery Services",["delivery servic","last mile"]),
("Logistics & Delivery","Logistics Companies",["logistic","freight","shipping","cargo"]),
("Printing & Business Services","Large-Format Printing",["large format","banner print","billboard print"]),
("Printing & Business Services","Digital Printing",["digital print"]),
("Printing & Business Services","Stamp Makers",["rubber stamp","stamp maker"]),
("Printing & Business Services","Embroidery & Branding",["embroider"]),
("Printing & Business Services","Signage & Branding",["signage","sign maker","signwrit","branding"]),
("Printing & Business Services","Graphic Designers",["graphic design"]),
("Printing & Business Services","Photocopying",["photocopy","copy cent"]),
("Printing & Business Services","Business Centres",["business cent","cyber cafe","cybercafe","internet cafe"]),
("Printing & Business Services","Secretarial Services",["secretarial","typing servic"]),
("Printing & Business Services","Printers",["print"]),
("Phones & Technology","Phone Repairers",["phone repair","screen replace","gsm repair"]),
("Phones & Technology","Phone Accessories",["phone accessor","gsm accessor"]),
("Phones & Technology","Phone Shops",["phone","gsm","mobile shop","telecom"]),
("Phones & Technology","Laptop Repairers",["laptop repair","computer repair"]),
("Phones & Technology","Computer Accessories",["computer accessor"]),
("Phones & Technology","Computer Shops",["computer"]),
("Phones & Technology","Electronics Repairers",["electronics repair","electronic repair","tv repair"]),
("Phones & Technology","Electronics Shops",["electronic"]),
("Phones & Technology","Satellite/Decoder Installers",["satellite","decoder","dstv","gotv","startimes"]),
("Phones & Technology","ATM Services",["atm"]),
("Phones & Technology","IT Support",["it support","it servic","it solution","tech support","network"]),
("Phones & Technology","Software Services",["software","app develop","web develop","technolog"]),
("Insurance & Finance","Insurance Brokers",["insurance broker"]),
("Insurance & Finance","Insurance Agents",["insurance agent"]),
("Insurance & Finance","Insurance Companies",["insurance","assurance","hmo"]),
("Insurance & Finance","Microfinance Banks",["microfinance","micro finance"]),
("Insurance & Finance","Cooperative Societies",["cooperative","co-operative","thrift society"]),
("Insurance & Finance","Bureau de Change",["bureau de change","forex"]),
("Insurance & Finance","Pension Consultants",["pension"]),
("Insurance & Finance","Mortgage Consultants",["mortgage"]),
("Insurance & Finance","Loan/Credit Businesses",["loan","credit compan","lending"]),
("Insurance & Finance","Investment Advisers",["investment","asset manage","securities","capital manage"]),
("Insurance & Finance","Financial Advisers",["financial advis","financial servic","finance compan"]),
("Insurance & Finance","POS Agents",["pos agent","point of sale"]),
("Insurance & Finance","Banking Agents",["bank"]),
("Real Estate & Property","Estate Surveyors",["estate surveyor","valuer","valuation"]),
("Real Estate & Property","Property Developers",["property develop","real estate develop","housing develop","estate develop"]),
("Real Estate & Property","Facility Managers",["facility manage","facilities manage"]),
("Real Estate & Property","Property Managers",["property manage"]),
("Real Estate & Property","Shortlet Operators",["shortlet","short let","short-term rental","short term apartment"]),
("Real Estate & Property","Serviced Apartments",["serviced apartment","apartment building","apartment hotel"]),
("Real Estate & Property","Property Investment Companies",["property investment","real estate investment"]),
("Real Estate & Property","Estate Agents",["estate agent","realtor","real estate","propert","letting agent"]),
("Professional Services","Law Chambers",["law firm","chambers","legal practitioner","solicitor","barrister","attorney","legal"]),
("Professional Services","Lawyers",["lawyer"]),
("Professional Services","Auditors",["audit"]),
("Professional Services","Tax Consultants",["tax"]),
("Professional Services","Accountants",["account","bookkeep"]),
("Professional Services","Architects",["architect"]),
("Professional Services","Quantity Surveyors",["quantity surveyor"]),
("Professional Services","Surveyors",["surveyor"]),
("Professional Services","Engineers",["engineer"]),
("Professional Services","HR Consultants",["human resource","hr consult"]),
("Professional Services","Recruitment Agencies",["recruit","staffing","employment agency"]),
("Professional Services","Public Relations Consultants",["public relations","pr agency","pr consult"]),
("Professional Services","Marketing Consultants",["marketing","advertis","media agency","brand consult"]),
("Professional Services","Training Consultants",["training cent","training institute","training consult","capacity build"]),
("Professional Services","Management Consultants",["management consult","business consult","consultan","consulting"]),
("Events & Creative Services","Balloon Decorators",["balloon"]),
("Events & Creative Services","Event Decorators",["event decor","decorator"]),
("Events & Creative Services","Event Planners",["event plan","event manage","wedding plan","event servic"]),
("Events & Creative Services","Chair & Table Rentals",["chair rental","table rental","chair hire"]),
("Events & Creative Services","Canopy Rentals",["canopy","marquee","tent rental"]),
("Events & Creative Services","Sound System Providers",["sound system","pa system","audio rental"]),
("Events & Creative Services","Event Lighting",["event lighting","stage light"]),
("Events & Creative Services","DJs",["disc jockey","deejay"]),
("Events & Creative Services","MCs",["master of ceremon","compere"]),
("Events & Creative Services","Videographers",["videograph","video product","film product","cinematograph"]),
("Events & Creative Services","Photo Studios",["photo studio","photography studio"]),
("Events & Creative Services","Photographers",["photograph"]),
("Events & Creative Services","Invitation/Card Printers",["invitation","card print"]),
("Events & Creative Services","Souvenir Vendors",["souvenir"]),
("Events & Creative Services","Gift Shops",["gift"]),
("Events & Creative Services","Event Florists",["florist","flower"]),
("Events & Creative Services","Event Rental Companies",["rental","hire servic"]),
("Catering & Events Food","Private Chefs",["private chef","personal chef"]),
("Catering & Events Food","Outdoor Catering",["outdoor catering"]),
("Catering & Events Food","Corporate Catering",["corporate catering"]),
("Catering & Events Food","Meal Preparation Services",["meal prep","meal plan"]),
("Catering & Events Food","Drinks Vendors",["drinks vendor","cocktail","bartend","mixolog"]),
("Catering & Events Food","Caterers",["cater"]),
("Baking & Desserts","Cake Makers",["cake"]),
("Baking & Desserts","Cupcake Businesses",["cupcake"]),
("Baking & Desserts","Pastry Shops",["pastry","patisserie"]),
("Baking & Desserts","Small-Chops Vendors",["small chops","smallchops"]),
("Baking & Desserts","Ice Cream Shops",["ice cream","gelato"]),
("Baking & Desserts","Yoghurt Shops",["yoghurt","yogurt"]),
("Baking & Desserts","Dessert Businesses",["dessert"]),
("Baking & Desserts","Confectionery",["confection","candy"]),
("Baking & Desserts","Bread Sellers",["bread"]),
("Baking & Desserts","Bakeries",["baker","bake"]),
("Bars & Entertainment","Beer Parlours",["beer parlour","beer parlor","palm wine"]),
("Bars & Entertainment","Sports Bars",["sports bar"]),
("Bars & Entertainment","Karaoke",["karaoke"]),
("Bars & Entertainment","Clubs",["night club","nightclub","nite club"]),
("Bars & Entertainment","Viewing Centres",["viewing cent"]),
("Bars & Entertainment","Pool/Snooker Centres",["snooker","pool club","billiard"]),
("Bars & Entertainment","Gaming Centres",["gaming","betting","bet9ja","arcade"]),
("Bars & Entertainment","Entertainment Centres",["entertainment","cinema","amusement","movie theater"]),
("Bars & Entertainment","Recreation Centres",["recreation"]),
("Bars & Entertainment","Pubs",["pub"]),
("Bars & Entertainment","Lounges",["lounge"]),
("Bars & Entertainment","Bars",["bar"]),
("Food & Restaurants","Shawarma",["shawarma","shawama"]),
("Food & Restaurants","Suya",["suya","balangu","asun"]),
("Food & Restaurants","Pizza Outlets",["pizza"]),
("Food & Restaurants","Burger Outlets",["burger"]),
("Food & Restaurants","Chicken Shops",["chicken"]),
("Food & Restaurants","Seafood Restaurants",["seafood"]),
("Food & Restaurants","Chinese/Asian Restaurants",["chinese","thai","japanese","sushi","asian","oriental"]),
("Food & Restaurants","Grills",["grill","barbecue"]),
("Food & Restaurants","Coffee Shops",["coffee"]),
("Food & Restaurants","Cafes",["cafe","bistro"]),
("Food & Restaurants","Breakfast Outlets",["breakfast","brunch"]),
("Food & Restaurants","Buka",["buka","mama put","local food","amala","ofada"]),
("Food & Restaurants","Canteens",["canteen","cafeteria","food court"]),
("Food & Restaurants","Food Delivery Businesses",["food delivery","meal delivery"]),
("Food & Restaurants","Fast Food",["fast food","fastfood","takeaway","take away"]),
("Food & Restaurants","Nigerian Restaurants",["nigerian","african restaurant"]),
("Food & Restaurants","Food Vendors",["food vendor","food servic","food product","eatery","kitchen"]),
("Food & Restaurants","Restaurants",["restaurant","diner","eater"]),
("Fashion & Clothing","Shoe Repairers",["shoe repair","cobbler"]),
("Fashion & Clothing","Shoe Shops",["shoe","footwear","sneaker"]),
("Fashion & Clothing","Handbag Shops",["handbag","bag shop","luggage"]),
("Fashion & Clothing","Jewellery Shops",["jewel","bead"]),
("Fashion & Clothing","Bridal Wear",["bridal","wedding dress","wedding gown"]),
("Fashion & Clothing","Traditional Wear Designers",["traditional wear","agbada","kaftan","aso oke","ankara","native wear"]),
("Fashion & Clothing","Lace/Fabric Sellers",["lace"]),
("Fashion & Clothing","Fabric Shops",["fabric","textile"]),
("Fashion & Clothing","Thrift/Pre-Owned Clothing",["thrift","okrika","second hand","pre-owned"]),
("Fashion & Clothing","Children's Clothing",["children's cloth","kids cloth","baby cloth"]),
("Fashion & Clothing","Men's Fashion",["men's cloth","menswear","men's wear","men's fashion"]),
("Fashion & Clothing","Alteration Services",["alteration"]),
("Fashion & Clothing","Tailors",["tailor","seamstress","sewing"]),
("Fashion & Clothing","Fashion Designers",["fashion design","couture","fashion house"]),
("Fashion & Clothing","Fashion Accessories",["accessor"]),
("Fashion & Clothing","Boutiques",["boutique","clothing store","cloth","apparel","fashion","wear"]),
("Agriculture & Food Supply","Veterinary Services",["veterinar","vet clinic"]),
("Agriculture & Food Supply","Pet Grooming",["pet groom","dog groom"]),
("Agriculture & Food Supply","Dog Training",["dog train"]),
("Agriculture & Food Supply","Pet Boarding",["pet boarding","kennel"]),
("Agriculture & Food Supply","Pet Food Suppliers",["pet food","dog food"]),
("Agriculture & Food Supply","Poultry Feed Sellers",["poultry","feed mill"]),
("Agriculture & Food Supply","Animal Feed Suppliers",["animal feed","livestock feed"]),
("Agriculture & Food Supply","Livestock Suppliers",["livestock","abattoir"]),
("Agriculture & Food Supply","Agricultural Input Dealers",["agricultur","agro","fertiliz"]),
("Water & Utilities","Sachet Water Producers",["sachet water","pure water"]),
("Water & Utilities","Bottled Water Producers",["bottled water","table water","water factory"]),
("Water & Utilities","Water Delivery",["water delivery","water supply"]),
("Water & Utilities","Plumbing Suppliers",["plumbing material","plumbing supply"]),
("Hospitality","Guest Houses",["guest house","guesthouse","bed and breakfast"]),
("Hospitality","Lodges",["lodge","motel"]),
("Hospitality","Conference Centres",["conference"]),
("Hospitality","Meeting/Training Facilities",["meeting room","coworking","co-working","workspace"]),
("Hospitality","Event Centres",["event cent","event venue","banquet","hall"]),
("Hospitality","Hotels",["hotel","suites","resort"]),
("Retail & Groceries","Frozen Food Shops",["frozen"]),
("Retail & Groceries","Meat Shops",["butcher","meat shop","meat store"]),
("Retail & Groceries","Fish Sellers",["fish seller","fish market","fish shop"]),
("Retail & Groceries","Fruit & Vegetable Sellers",["fruit","vegetable","greengrocer"]),
("Retail & Groceries","Wine & Drinks Shops",["wine","liquor","drinks store","beverage","spirits"]),
("Retail & Groceries","Water Sellers",["water seller","water shop"]),
("Retail & Groceries","Cosmetics Shops",["cosmetic"]),
("Retail & Groceries","Baby Product Shops",["baby","infant"]),
("Retail & Groceries","Stationery Shops",["stationer","bookshop","book shop","bookstore","office supply"]),
("Retail & Groceries","Pet Shops",["pet shop","pet store"]),
("Retail & Groceries","Household Goods Shops",["household","houseware","home goods"]),
("Retail & Groceries","Supermarkets",["supermarket","hypermarket","superstore","shoprite","ebeano"]),
("Retail & Groceries","Mini-Marts",["mini mart","minimart","mini-mart","mart"]),
("Retail & Groceries","Convenience Stores",["convenience"]),
("Retail & Groceries","Provision Stores",["provision","grocer","market","general store"]),
("Health & Medical","Opticians",["eye care","eyecare","spectacle"]),
("Home Services","Appliance Repair",["washer","dryer repair","washing machine"]),
("Fashion & Clothing","Bridal Wear",["wedding store","wedding shop"]),
("Printing & Business Services","Signage & Branding",["sign shop","signboard"]),
("Furniture & Interiors","Mattress Shops",["bedding"]),
("Construction & Building","Building Material Shops",["paint store","paint shop","plumbing store"]),
("Construction & Building","Electricians",["electrical installation","electrician","electrical works"]),
("Retail & Groceries","Pet Food & Accessories",["pet supply","pet accessor"]),
("Insurance & Finance","Banking Agents",["financial institution"]),
("Logistics & Delivery","Logistics Companies",["transportation","transport compan"]),
("Other Local Services","Key Cutting",["key duplication"]),
("Hospitality","Serviced Apartments",["apartment","apartments","homes and suites"]),
("Professional Services","Management Consultants",["corporate office","professional services","business services"]),
("Health & Medical","Clinics",["health services","health care","healthcare"]),
("Furniture & Interiors","Furniture Shops",["home and living","home & living"]),
("Automotive","Mechanics",["automotive"]),
("Retail & Groceries","Provision Stores",["retail","wholesaler","store","shop"]),
("Other Local Services","Watch Repair",["watch repair"]),
("Other Local Services","Key Cutting",["key cutting"]),
("Other Local Services","Advertising Agencies",["advertis"]),
("Other Local Services","Branding Companies",["branding"]),
("Other Local Services","Repair Services",["repair"]),
]

_compiled = [(g, s, [k.lower() for k in ks]) for g, s, ks in RULES]


def classify(label, name=""):
    blob = " " + re.sub(r"\s+", " ", ((label or "") + " " + (name or "")).lower().replace("/", " ")) + " "
    for g, s, keys in _compiled:
        for k in keys:
            if k in blob:
                return g, s
    return "Other Local Services", "Unclassified (needs review)"


if __name__ == "__main__":
    tests = [("Pharmacy", "Medplus"), ("Barber shop", "Prince Barbing"), ("Dry cleaner", "CleanAce"),
             ("Real estate agency", "Nobility Estates"), ("Vulcanizer", ""), ("Beauty salon", "Edith"),
             ("Fast Food", "Mr Biggs"), ("Church", "St Agnes"), ("Auto repair shop", "Tritan"),
             ("Boutique", "Sophisticat"), ("Plumber", "ALEF"), ("Event venue", "G3 Event Centre"),
             ("Nursery school", "Little Angels"), ("Generator repair", ""), ("Solar installation", "Sunfit"),
             ("Supermarket", "Market Square"), ("Hotel", "L'Eola"), ("Lawyer", "Lawlinks")]
    for t in tests:
        print(t, "->", classify(*t))
